sudo: required # 관리자 권한 갖기

language: generic # 언어(플랫폼)

services:
  - docker

before_install: # 스크립트를 실행할 환경
  - echo "start"
  - docker build -t hjy/docker_react -f Dockerfile.dev .

script: # 실행할 스크립트
  - docker run -e CI=true hjy/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-test"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-810212283950"
  bucket_path: "docker-test"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY



